pipeline {
    agent {
      node {
        label 'master'
      }
    }
    environment {
        DEV_PROJECT = "python-app"
        APP_NAME = "python-hello"
        APP_GIT_URL = "https://github.com/ShaktiAhad/Test-deployment.git"
        CONTEXT_DIR = "test"
    }
    stages {
        stage('Launch new app in DEV env') {
                steps {
                    sh '''   
                        oc project ${DEV_PROJECT}
                        sleep 5
                    '''
                }
            }
        stage('checking the app exist or not') {
            steps {
                script{
                    openshift.withCluster() {
                        openshift.withProject( "${DEV_PROJECT}" ) {
                            script {
                                if (openshift.selector("bc", "${APP_NAME}").exists()) {
                                    sh '''
                                        oc project ${DEV_PROJECT}
                                        oc start-build ${APP_NAME}
                                        sleep 120
                                        oc expose svc/${APP_NAME}
                                    '''
                                } else {
                                    sh '''
                                        oc new-app --name ${APP_NAME} python:latest ${APP_GIT_URL} --context-dir ${CONTEXT_DIR}
                                        sleep 120
                                        oc expose dvc/${APP_NAME}
                                    '''
                            }
                        }
                    }
                }
            }
        }
        }


        stage('Wait for S2I build to complete') {
                steps {
                    script {
                        openshift.withCluster() {
                            openshift.withProject( "${DEV_PROJECT}" ) {
                                def bc = openshift.selector("bc", "${APP_NAME}")
                                bc.logs('-f')
                                def builds = bc.related('builds')
                                builds.untilEach(1) {
                                    return (it.object().status.phase == "Complete")
                                }
                            }
                        }
                    }
                }
            }

        stage('Wait for deployment in DEV env') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject( "${DEV_PROJECT}" ) {
                            echo "Deployment is done!"
                            }
                        }
                    }
                }
            }
        }
    }
